changes the secret id which function needs to access within code
software.amazon.awssdk.services.secretsmanager.model.SecretsManagerException: User: arn:aws:sts::275416279984:assumed-role/Matlab-SpringbootApiLambd-SpringBootApiLambdaCdkPoc-a24eR7linbYK/ProductCatalogSbApiLambda is not authorized to perform: secretsmanager:GetSecretValue on resource: lab/secretMGPOC/MySQL-hai33O because no identity-based policy allows the secretsmanager:GetSecretValue action (Service: SecretsManager, Status Code: 400, Request ID: 6343bdbe-1486-46e8-9a15-5ec3d2405cbb)