granting function to read a secret that we need for db access details
software.amazon.awssdk.services.secretsmanager.model.SecretsManagerException: User: arn:aws:sts::275416279984:assumed-role/Matlab-SpringbootApiLambd-SpringBootApiLambdaCdkPoc-a24eR7linbYK/ProductCatalogSbApiLambda is not authorized to perform: secretsmanager:GetSecretValue on resource: lab/secretMGPOC/MySQL-hai33O because no identity-based policy allows the secretsmanager:GetSecretValue action (Service: SecretsManager, Status Code: 400, Request ID: 23df78c1-2029-40fa-b92c-830006e74458)